# NavSat Transform Node parameters
# Converts GPS (NavSatFix) to local odometry (/odometry/gps)

navsat_transform_node:
  ros__parameters:
    use_sim_time: true
    frequency: 30.0
    delay: 0.0
    magnetic_declination_radians: 0.0   # Simulation
    yaw_offset: 1.570796327             # Gazebo ENU X=East -> ROS yaw=0 North conversion
    zero_altitude: true
    broadcast_cartesian_transform: true
    publish_filtered_gps: true
    use_odometry_yaw: false             # Use IMU yaw directly 
    base_link_frame: base_footprint     # Prevents tf lookup failures since default is base_link
    wait_for_datum: true                # Explicitly wait for the datum fixed point
    datum: [39.925050, 32.836956, 0.0]  # Lat, Lon, Yaw
